# Generated by Django 3.1 on 2020-08-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='link',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
